---

name: Publish

on: [push]

jobs:
  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade build
          python -m pip install --upgrade twine
      - name: Build and publish package
        run: make publish
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{secrets.PYPI_API_TOKEN}}
